@ContosoPizzaWebAPI_HostAddress = http://localhost:5161

GET {{ContosoPizzaWebAPI_HostAddress}}/pizza/
Accept: application/json
###
GET {{ContosoPizzaWebAPI_HostAddress}}/pizza/1
Accept: application/json
###
GET {{ContosoPizzaWebAPI_HostAddress}}/pizza/5
Accept: application/json
###
POST {{ContosoPizzaWebAPI_HostAddress}}/pizza/
Content-Type: application/json

{
    "name": "Hawaii",
    "isGlutenFree": false
}

###

###
PUT {{ContosoPizzaWebAPI_HostAddress}}/pizza/3
Content-Type: application/json

{
    "id": 3,
    "name": "Hawaiian",
    "isGlutenFree": false
}

###
GET {{ContosoPizzaWebAPI_HostAddress}}/pizza/3
Accept: application/json

###
DELETE {{ContosoPizzaWebAPI_HostAddress}}/pizza/3

###