@ContosoPizzaWebAPI_HostAddress = http://localhost:5161

GET {{ContosoPizzaWebAPI_HostAddress}}/pizza/
Accept: application/json
###
GET {{ContosoPizzaWebAPI_HostAddress}}/pizza/5
Accept: application/json
###